# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bzUCFQyyDZdSxyhEsV6A3pFir8Xulhfn
"""

question 1
ENTER ANY STRING :what is your name is
{'what': 1, 'is': 2, 'your': 1, 'name': 1}
   

Question 2
ENTER THE DAY:4
Enter the month:4
Enter a year between 1800 and 2025:2004
5 / 4 / 2004


Question 3
enter the elements with a space:
5 6 
list: 5 6 
the required result is : [(5.0, 25.0), (6.0, 36.0)]


Question 4
Enter the grade point:
9
Your grade is 'A' and Excellent performance


Question 5
ABCDEFGHIJK
 ABCDEFGHI
  ABCDEFG
   ABCDE
    ABC
     A


Question 6
Enter your sid:
34
Enter name: 
Rithik
Do you want to enter another student entry(Y or N):Y
Enter sid: 35
Enter name: Akash
Do you want to enter another student entry(Y or N):N
<a>
 {34: 'Rithik', 35: 'Akash'}
<b>
 {35: 'Akash', 34: 'Rithik'}
<c>
 {34: 'Rithik', 35: 'Akash'}
Search Name with SID:
34
<d>
 Rithik
Question 7
ENTER THE NUMBER OF TERMS IN THE SERIES:
7
Fibonacci sequenceL: 
0
1
1
2
3
5
8
AAVERAGE OF THE RESULTANT FIBONACCI SERIES IS:  2.857142857142857
Question 8
<a>
 {1, 3, 5, 6, 8}
<b>
 {3, 6, 8, 9, 13, 17}
<c>
 {1, 2, 4, 5}
<d>
 {6, 7, 8, 9, 10}
<e>
 {10}
PS C:\Users\rithi\OneDrive\Desktop\practice>